### ISSUE TITLE
Feature request: better phishing protection usage

### ISSUE THREAD

**Issue by thisbethedev** [ray-lothian/Block-Site#10]
Hey, feature request here. 

I am using your addon to protect myself from phishing. So I use it kind off like uMatrix (similar to NoScript) where I unblock the web as I "discover" it. Meaning when I am about to visit an undiscovered site it gets blocked by this addon and I need to manually check the URL (see whether it is spelled right and not a phishing domain). When the URL is good, I want to be able to easily/quickly add it to the whitelist, as I will do this quite frequently. Clicking the addon icon would be a ok-solution (once [this bug](https://github.com/ray-lothian/Block-Site/issues/11) is fixed), but I would love if this plugin took it one step further in terms of UserExperience and had the following added to its blocking screen:  

- show the domain name with its TLD, without subdomain, path or params (big font size) in order to more easily and faster identify wrong typed/mispelled domains
- a button to add the blocked page to the whitelist, with generous wildcards, eg `*://*github.com*/*`. So it behaves like the addon icon.

And also: great addon, I love the simplicity!

**Comment by ray-lothian** [comment]
We are going to have it on the next release. Thanks for the suggestion. btw, never use `*://*github.com*/*`. Instead use `*://github.com*/*` and `*://*.github.com*/*`. The extension will generate the correct rules when the newly added "Add to Whitelist" button is pressed.

**Comment by thisbethedev** [comment]
Ok great. And yes, i screwed up the wildcards - Thanks for the headsup!
