### ISSUE TITLE
Instant close

### ISSUE THREAD

**Issue by WaGi-Coding** [ray-lothian/Block-Site#100]
I like this extension. Only thing i really dislike is that the autoclose cannot be instant. Minimum is 1 second (which ends up to be ~2 seconds). if you set it to eg 0.1 it will just bug out ^^ Can't you make this timer check every 100ms and support 100ms steps, or an instant close. Or if possible, don't even open the window at all?

Greetings

**Comment by ray-lothian** [comment]
Why dont you use the "close" keyword?

FAQ14; https://add0n.com/block-site.html
