### ISSUE TITLE
Whitelisting pages with addon icon adds the blocking-pages address

### ISSUE THREAD

**Issue by thisbethedev** [ray-lothian/Block-Site#11]
Clicking the addon icon while in whitelist mode only adds addon-address (`moz-extension://[...]/`) to the whitelist! I do not think that is intended and I would love to see it add the domain the user is about to access to the whitelist with a configurable wildcard setting for subdomains, paths and params instead.

**Comment by ray-lothian** [comment]
True, the warning message is changed. I am not going to perform any action though, since we already have the button in the page based on #10.
