### ISSUE TITLE
[REQUEST] A more reliable Close blocked page system.

### ISSUE THREAD

**Issue by gaveitatry2** [ray-lothian/Block-Site#113]
I"m using your extension on Google Chrome to block:
https://support.google.com/chrome/?p=help&ctx=keyboard#topic=7439538
from opening when I press the F1 key.

I have it set to "close".

However, it just opens up a Restricted page instead. If I change the "close after" 0 seconds to 1 seconds then it will eventually close after one second. But if I have it set to "close after 0 seconds" the restricted page remains open forever even though it is supposed to automatically close the page.

Could you make it so that 0 seconds ALWAYS closes the page, no matter what? Like have it automatically try to close the page ever 0.01 or 0.1 seconds until one second (0.9 seconds would be better) has passed and then stop? That way the page will close ASAP and never fail to close.

**Comment by Marastevenson** [comment]
La web https://umobix.com/  Es una web de hackeadores que te usurpan la ientidad hackeandote  el movil o ordenador y te roban las tarjetas de credito venc¡diendolas a terceros. En solo una día a mi me robaron más de 1000€

**Comment by gaveitatry2** [comment]
Instead of having the page open up a new tab and then auto close after a certain number of seconds, it would be nice if the new page tab never appeared in the first place. Or at least since 0 seconds auto close doesn't always work, and 1 second is a bit long, make it so that the page tries to close every 0.1 seconds and to that 9 times (0.9 seconds at most) before no longer attempting to close the page. That way 0.0 seconds can take 0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7 0.8, or 0.9 seconds depending on how lucky the user is, but will still be less than the next designation of 1.0 seconds.

**Comment by ray-lothian** [comment]
Zero disables the feature. For immediate closing, use the "close" keyword on the redirect box instead.

<img width="1454" alt="Screenshot 2023-08-26 at 04 13 57" src="https://github.com/ray-lothian/Block-Site/assets/29911230/98c0c877-ed26-4859-bc56-b065f2781b9f">

**Comment by gaveitatry2** [comment]
> Zero disables the feature. For immediate closing, use the "close" keyword on the redirect box instead.
> <img alt="Screenshot 2023-08-26 at 04 13 57" width="1454" src="https://user-images.githubusercontent.com/29911230/263451572-98c0c877-ed26-4859-bc56-b065f2781b9f.png">

1.) I already wrote that I used the "close". Do you think I am a liar? Do I need a screenshot to prove that I have close typed in that field?

2.) And if zero disables the feature, why does your addon write "(use zero for no automatic closing)." Last time I checked, in the English language, automatic closing and disables feature don't mean the same thing. 

3.) The entire point of my post was that 1 seconds is too long and 0 seconds doesn't work. It used to work. Maybe it works with some websites. But not the google support website that I listed. And the ENTIRE FREAKING POINT of this post WHICH YOU IGNORED is that it would be better to have less than 1 seconds, immediate close option that works and I OFFERED YOU THE METHOD OF HOW THAT CAN BE ACCOMPLISHED which is to have it try to close every 0.1 seconds. That way, at the very earliest, it will close in 0.0 or 0.1 seconds. But it will keep trying to close every 0.1 seconds until 0.9 seconds have passed. If it closes during that time, good, and it will stop trying to auto close after 0.9 seconds have passed. If it doesn't close during that time, it will stop trying to auto close after 0.9 seconds and the user will have to use 1-2 seconds instead. I don't know why this is so hard for you to understand. Basically I just want the tab to close faster than 1 second or to never open in the first place. "close" does NOT close the tab less than one second and in fact relies on the number of seconds which I can only set to 0 or 1. 1 being too long, 0 not closing. FRECKING HELL. DID YOU READ ANYTHING I WROTE IN THE ORIGINAL POST??????
