### ISSUE TITLE
Can't remove pause 'forever'

### ISSUE THREAD

**Issue by mmdescize9** [ray-lothian/Block-Site#115]
![image](https://github.com/ray-lothian/Block-Site/assets/143879377/f9981069-8774-4e7b-8691-d60fc7655e0d)

![image](https://github.com/ray-lothian/Block-Site/assets/143879377/27f11776-4bba-4614-9e9f-456acb7fc31f)

My pause periods is only 5 minutes which was working for a long time but suddenly, pause 'forever' showed up as well

**Comment by mmdescize9** [comment]
same issue, still doesn't work, I even reinstalled the extension

**Comment by ray-lothian** [comment]
It will be available on the next release.

**Comment by mmdescize9** [comment]
Ok thanks

**Comment by mmdescize9** [comment]
Will I need to reinstall to obtain the next release or will it happen automatically? And how long roughly do you think it will take? Thanks
