### ISSUE TITLE
Pause Blocking option still visible in Context Menu

### ISSUE THREAD

**Issue by Fabri983** [ray-lothian/Block-Site#131]
I can still see the Pause Blocking option even though it is disabled in the settings.
The only way to fix that is to tap Save Options every time mozilla firefox starts, but I don't like to do that, other than that it works fine with Resume Blocking.
The JSON clearly is showing that contextmenu-pause is false
![imagen](https://github.com/ray-lothian/Block-Site/assets/83408698/b0e4f952-fca0-4f4c-8f86-9137d7eb8655)
![imagen](https://github.com/ray-lothian/Block-Site/assets/83408698/3ff66ea6-3883-4764-ba44-116e393ba490)
![imagen](https://github.com/ray-lothian/Block-Site/assets/83408698/2f40a8bf-84b6-49eb-85ea-01af3ec863a4)

**Comment by gamma19** [comment]
Any updates about this?
