### ISSUE TITLE
unblock keeps redirecting to restricted access page. 

### ISSUE THREAD

**Issue by Frostleban** [ray-lothian/Block-Site#132]
It stopped since the last update. Filling in the password no longer unblocks websites, it refreshes, then redirects to the 'restricted access' page.
It does NOT give the 'wrong password' pop-up when I fill in the correct password, it simply doesn't work. 

Filling in an incorrect password does give the pop-up as expected. 

FF version 126.0.1 (64-bits)
Block site latest update May 27th 2024

**Comment by ray-lothian** [comment]
I am not able to reproduce this. Have you tried restarting your browser?

**Comment by Frostleban** [comment]
Jup. Restarting browser, restarting PC, getting to latest update, tried a bunch of things. I'll see if I can get some more data today.

**Comment by ray-lothian** [comment]
Also you can try the extension on a clean profile to make sure it is not a conflict with other extensions;

https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles

**Comment by Frostleban** [comment]
I've disabled other extensions. Still does not work. 
Retrying the password gave me something weird though:
it gives a 'blocked since' time. And that time is jumping around. it says it's blocked since a few minutes, but when i re-input the master password it gives a new time. All the times are from the future as wel. Like 30-5-2024 00:08:18 While it's 00:05 here.

I've added a new site to the blocklist, there it only blocks the first time. Re-inputting the password a few times does eventually give me access.

**Comment by Frostleban** [comment]
some more things: 
I deleted and re-added the rules: still doesn't work. 
funny thing is: even when I pause the blocking temporarily, it still keeps blocking reddit.
I added another site to the list, and there it actually does pause the blocking.
I think something broke my browser lol.

**Comment by hitrzajc** [comment]
``` even when I pause the blocking temporarily, it still keeps blocking ```

same with me. My theory is, if you first click on the resume blocking and then on pause blocking, it breaks

**Comment by awilson8487** [comment]
I am having the same issues. I created a new profile on Firefox 126.0.1 (64-bit) and installed Block Site and set the redirect to Wikipedia and blocked YouTube. The redirect worked till I paused blocking for 5 minutes, And now it keeps pulling up "Restricted Access" page instead of the redirected Wikipedia page and does not unblock the content. My issues also started occurring a few days ago.

**Comment by Frostleban** [comment]
Didn't know about the redirect option, but that is indeed also not working on my end. 
Also set a redirect page, but it only refreshes/redirects to the same restricted access page in stead of the target page.

**Comment by Frostleban** [comment]
Update because something has changed. Redirect now works. If i type in a blocked website, it instantly redirects to the new URL. Only problem is if I click pause blocking, it now redirects to the Restricted Access page in stead of allowing the original page.

**Comment by falkanson** [comment]
I have the same issue, when pressing the temporary unblock button in the context menu the website isn't unblocked

**Comment by ray-lothian** [comment]
It seems like there's a problem with the declarativeNetRequest implementation on Firefox. This issue should be resolved in the `0.5.2.1` release.

**Comment by mathensilva** [comment]
version 0.5.2.1, when in reverse mode, the extension doesn't get the full url path, version 0.5.2.1, the last one it was working great
