### ISSUE TITLE
Get this every time

### ISSUE THREAD

**Issue by Cryo85** [ray-lothian/Block-Site#134]
Hi i get this error every time when i start the Firefox. Please see image in attachment.
Someone have idea what can it be?
Grts.
![2024-06-08_20h58_52](https://github.com/ray-lothian/Block-Site/assets/172143416/64a94273-dca2-46ee-81fd-fcc6f2beb9c4)

**Comment by ray-lothian** [comment]
Do not add the website manually. instead open it in a browser tab then press the extension's toolbar button.
