### ISSUE TITLE
The trailing / in the rules causes the blocking to not work sometimes

### ISSUE THREAD

**Issue by x-ji** [ray-lothian/Block-Site#16]
When adding a website, a `/` is always added automatically to the end. However, this causes the blocking to sometimes fail:

For example, if I want to block, e.g. www.reddit.com/r/soccer

If I enter the URL, it will become https://www.reddit.com/r/soccer/*

When I visit the website, since the URL in the browser is actually https://www.reddit.com/r/soccer, the rule doesn't match, and the blocking doesn't happen.

Only when I try to visit a subpage, e.g. https://www.reddit.com/r/soccer/comments/aaa, does the blocking happen.

This is especially problematic on Android. You can easily reproduce the issue with Firefox Beta on Android, I believe.

I think this should be easy to fix?

**Comment by ray-lothian** [comment]
If the rule contains "://", the extension is not going to alter the rule. Alternatively wait for the new release and set regular expression rules.
