### ISSUE TITLE
domain range blocking

### ISSUE THREAD

**Issue by MvGulik** [ray-lothian/Block-Site#17]
Is it possible to block a particular domain type ?

Like for example "*.google.com/".
... (_ie: blocking all url's that contain ".google.com" in the domain name_) ... + (_including the domain without trailing/closing "/"_)
... (_or, for example blocking any and all ".com" domains_)

Would be a nice thing if this was possible ... _especial this week_.

**Comment by ray-lothian** [comment]
note 6 on the options page?
![Screen Shot 2019-10-12 at 8 41 00 AM](https://user-images.githubusercontent.com/29911230/66697333-1c0efc00-ecc4-11e9-9332-8c6807c9d648.png)

**Comment by MvGulik** [comment]
Oops, sorry. I overlooked that part.
... 
Thanks, got it working.

(closing)
