### ISSUE TITLE
Feature Request: Pause Blocking 

### ISSUE THREAD

**Issue by Delphik** [ray-lothian/Block-Site#18]
Many of the sites I block for productivity I would like to access on leisure time, and having to re-enter master passwords makes for a bad UX. The ability to pause blocking on-demand would make that use case considerably smoother

**Comment by ray-lothian** [comment]
thanks for the feature request. We are going to have this on the next release;
![Screen Shot 2019-10-23 at 3 22 36 PM](https://user-images.githubusercontent.com/29911230/67402866-b4e52780-f5a0-11e9-9191-61d7b326d49b.png)
