### ISSUE TITLE
Domain block note/info.

### ISSUE THREAD

**Issue by MvGulik** [ray-lothian/Block-Site#19]
After a bit of testing it seems that the advised "`*://*keyword*/*`" variation, to specify domain-part only blocks, also acts on the url path.

In general this is not something that would show up quickly.
(_really rare, when one is using something like "`*://*google.com*/*`"_)

But when trying to block a specific net designator (ie: ".com" or ".nl") this will have a higher level of triggering the occasional bad blocking cases when "com" or "nl" is precent in the url-path.
(_a issue for sites that make use of random id's in there paths. Like for example google's gmail pages_)

Example:
- Block spec: "`*://*.nl*/*`"
- Url: "www.google.nl": Blocked - as expected.
- Url: "www.google.com/nl": Blocked - not expected. (+ _seems to also ignore the leading dot in the block spec_)

Workaround:
Although I could not find any info about potential character escaping support in/for Block-site. Escaping the leading dot in the domain-block spec seems to do the trick.
- Block spec: "`*://*\.nl*/*`"
- Url: "www.google.nl": Blocked - as expected.
- Url: "www.google.com/nl": Not blocked - as expected.
(_as far as I know dots are not used (allowed?) in the url path part. rendering the escaped-dot block variant 'virtual' foolproof_)

The issue, if any ... not sure.
Could be seen as (the intended) domain-blocks being a bit to greedy.
Or the domain-block doc needing a bit of additional info.

**Comment by ray-lothian** [comment]
True, the wildcard matching is not perfect, but it is simple to use and in most cases, it just works. To fix the issue, support for regular expression matching is added. As of the next release, it is possible to start a rule with `R:` keyword to let the extension know that this is a regular expression rule. With this new feature, you can write complex rules that can differentiate between the hostname and pathname parts.

**Comment by MvGulik** [comment]
Looking forward to regex (_any flavor_) support. :)
