### ISSUE TITLE
Time Defines for Blocking Sites

### ISSUE THREAD

**Issue by MicroSuck0123** [ray-lothian/Block-Site#2]
Hey, really like this extension, much better than a couple of the others I tried, which were shockingly bad. 

But I do have one issue: the "only block sites between" feature doesn't seem to be working. When I type in a time into the box, the -- get replaced by what I type, but when I get to the last pair of --, it no longer takes the input and replaces the dashes. Then it doesn't save any of what I entered and it all reverts to --. 

Sort of the same story with days, that doesn't seem to affect what is blocked/not blocked, everything on the list is still blocked regardless of changing that setting. I'm also not sure whether those are days that it _is_ blocked or days that it isn't blocked, because right next to Days: it says Exception List:, but the instructions in the FAQ seem to imply that those, like the time, are also specifying when they _are_ blocked. Any help navigating these issues would be awesome. Thanks in advance!

**Comment by Congrammers** [comment]
Also had similar issue on modifying the time .

and even if I successfully modified the day blocking should be active which is on weekdays, it's still blocking on weekends.
![Screenshot_20190512_205003](https://user-images.githubusercontent.com/10162227/57582461-b097e700-74f7-11e9-9739-63bd511d3c16.png)

**Comment by ray-lothian** [comment]
For the schedule to work, you need to have all the values. In your screenshot, the "From" and "to" is empty.
