### ISSUE TITLE
Time Restriction to Block Sites Happens 24/7

### ISSUE THREAD

**Issue by gateslm** [ray-lothian/Block-Site#21]
While using the extension, the site does not block the sites within a certain time but blocks all the time. Only the sites I have listed are blocked 24/7, instead of the time frame I have listed. 

Attached is my preference file, unless I have something set wrong. I changed it from `.json` to `.txt` so I could upload it here. 
[block-site-preferences-3.txt](https://github.com/ray-lothian/Block-Site/files/3909380/block-site-preferences-3.txt)

**Comment by ray-lothian** [comment]
Thanks for the report. Please reopen if it is not fixed by the next release.
