### ISSUE TITLE
Bug: Doesn't work on Kiwi browser Android. 

### ISSUE THREAD

**Issue by n3h3m** [ray-lothian/Block-Site#34]
Kiwi browser is the Chrome clone for Android and it supports all Chrome extensions. I already use extensions like uBlock Origin, HoHSER etc. 

When I try block-site, the extensions doesn't detect the current tab but sends empty notification that

"Not tab with id: 50."

**Comment by ray-lothian** [comment]
I just tried v0.2.9 on Kiwi browser and it works for me. I can block sites using the browser-action's button just fine.
