### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by rs4231199** [ray-lothian/Block-Site#37]
[This link](https://www.google.com/search?client=firefox-b-d&q=fd) opens even though I have disabled the `*://*.google.com/*`.
I'm reporting this because there might be other similar links which passes through the filter.

**Comment by ray-lothian** [comment]
It blocks the link if I only have this rule on my list. So I guess, there is a rule that messes up the filtering. Can you share your exported JSON file?

**Comment by rs4231199** [comment]
Oops. It was caused by a rule I had in *schedule blocking*. Removing that rule fixed it.
Thanks for the help. And thanks for keeping this extension simple.
