### ISSUE TITLE
How can I deactivate the "insert master password to unlock" option in the blocked page? 

### ISSUE THREAD

**Issue by Hardom** [ray-lothian/Block-Site#42]
I just wanted the alert text and nothing more, like if you use the app to redirect to another url, you're essentially permanently blocked from a website, while on blocked page mode, you can still insert the master password to get yourself out

**Comment by ray-lothian** [comment]
Use the "Custom CSS" section to hide sections that you do not want. e.g.:

```css
footer {display: none !important}
```
