### ISSUE TITLE
Block-Site completely ignores anything I tell it to do in any way

### ISSUE THREAD

**Issue by nicodipietro** [ray-lothian/Block-Site#43]
Hello,
I would be grateful if you could help me to make Block-Site work.
I installed it (tried several times, also restarting Firefox) but it does not accept any input.

Icon method:
I visit a website I want to block, click on the W icon, the popup asks me confirmation that I want to block that website, I accept, but nothing changes. It's as though I never did the procedure.
I open Block-Site settings, manually enter the url of a website I want to block, I click the Add button but it ignores my clicks, as if I didn't write anything in the field, or as if I didn't click the button. I tried with several different sites, both writing and not writing "http" and "www".
I create a TXT file of files to block according to instructions, I click on the "Import Rules (TXT File)" button, but it does absolutely nothing, as if the button doesn't exist.

Any clue of what might be going on?
Thanks so much.

**Comment by GreatestFool** [comment]
When you added a site manually in the gui, did you remember to press _save_ at the bottom of the page? It will not save it otherwise.

**Comment by nicodipietro** [comment]
Hello @GreatestFool , thanks so much for replying.
Yes, the 'save' button was also unclickable. Everything was frozen. But then I figured it out because many other apps were frozen too: my Firefox was broken. I reinstalled it and everything worked.
Thanks again.

**Comment by GreatestFool** [comment]
Good to know that it was something else that caused this, considering this is solved, you should also close the issue since there is no more to be done.

**Comment by nicodipietro** [comment]
> 
> 
> Good to know that it was something else that caused this, considering this is solved, you should also close the issue since there is no more to be done.

Right, thank you @GreatestFool 
I'm going to do that now. All the best.

**Comment by CFoltin** [comment]
Hi,

I had exactly the same problem, that it is not at all obvious, that you have to press the "save"-button. It seems that the plugin just doesn't work. I started to search in direction of incompatibilities between NoScript or AdBlock or the like. 
It would be *very* helpful to have a visual indication that the changes have to be saved.
Proposals: 

- changing options will add a red message beneath the change, that it has to be saved.
- The browser title get's an "*" indicating, that there are unsaved changes
- Implement an autosave as default

Be aware, that the save button is hidden within a section called "Tools". Please make it more obvious having an own section called "Save changes" or the like.

Thanks anyway for the extension,

Chris

**Comment by GreatestFool** [comment]
A warning dialogue pop-up when trying to close the page if you have unsaved settings where you can choose to leave regardless or stay on the page would also be a nice touch.
