### ISSUE TITLE
License of this project

### ISSUE THREAD

**Issue by paulusasol** [ray-lothian/Block-Site#48]
As far as I can tell, there is no mention of a license anywhere in this repository (though I might just be tired).

Could you please mention the license in the repository?
[The GNU project recommends to put a notice in every source file](https://www.gnu.org/licenses/gpl-faq.html#NoticeInSourceFile), but this is your choice.

Thanks!

Edit: Some removals, and minor edits, didn't realize when posting that the license of this project is mentioned on addons.mozilla.org.

**Comment by ray-lothian** [comment]
I added the `LICENSE` file to the root directroy. I'll make sure to have it included in all new versions.
