### ISSUE TITLE
list of domains instead of  1 by 1 entry

### ISSUE THREAD

**Issue by gvmelle** [ray-lothian/Block-Site#5]
Could it be possible to have just one big textbox to fill in domain to block or allow like the chrome extension SiteBlock 0.2.4. ? That way it is far easier to keep a list somewhere offline or copy it from one to another browser.

In Siteblock 0.2.4 it goes like this:
**Help**
List the websites you want to block, one per line. For example:

cnn.com
nytimes.com
google.com/news

If you would like to block all sites except for a select few, enter a '*' on the first line and the websites you wish to allow with a '+' before each line. For example:

\*
+stackoverflow.com
+msdn.microsoft.com

**Comment by ray-lothian** [comment]
We will have the import button and the instruction on the next release. Please reopen afterwards if there is a need for enhancement.
