### ISSUE TITLE
Reverse Mode with Scheduling

### ISSUE THREAD

**Issue by mbmatt11** [ray-lothian/Block-Site#50]
Hello,

I'm trying to block all sites, except for 1 site for 1 hour a day. I thought if i said to block that 1 site for the specified hours each day, the reverse mode would reverse it so that is the only site available during those hours and no other sites are available outside of those hours. Basically it would be block all site except for this site during that hour.

What I'm gathering is the schedule just turns off the extension all together. 

I'm wondering, is there any way to achieve what I'm trying to do - have all site blocked all hours of the day, except for one hour of the day where just one site is available.

**Comment by ray-lothian** [comment]
So you just want to allow one-site-access for a specified period and no blocking for other times? This is exactly what is expected if you set the schedule for the period and have this site on the blocking list.

**Comment by ray-lothian** [comment]
> I'm wondering, is there any way to achieve what I'm trying to do - have all site blocked all hours of the day, except for one hour of the day where just one site is available.

I added a new FAQ for this part; see FAQ 17. https://add0n.com/block-site.html?drf
