### ISSUE TITLE
Questions (feature request): how to block root only? But allow child.

### ISSUE THREAD

**Issue by 9527KGG** [ray-lothian/Block-Site#52]
For example, I want to block
https://www.youtube.com/

But allow
https://www.youtube.com/results?search_query=abc

Thanks.

**Comment by ray-lothian** [comment]
You need to add a regex rule. For YouTube it would be
```
R:^https://www\.youtube\.com/?$
```

Dont forget to remove YouTube related rules and press the "Save" button

**Comment by 9527KGG** [comment]
Thanks. It works. 

I've one more Q: is it possible to sync setting among different chrome across different machine?

Thanks.

**Comment by ray-lothian** [comment]
You need to use managed storage; https://add0n.com/block-site.html#faq15
