### ISSUE TITLE
Timer + iframe closes parent tab

### ISSUE THREAD

**Issue by Demindiro** [ray-lothian/Block-Site#6]
How to reproduce:
- Go to any site with embedded content in an `iframe` (e.g. an article with a YouTube link such as https://www.diffen.com/difference/Router_vs_Switch)
- Wait

Expected behaviour:
- `iframe` contents are blocked but the parent tab remains open.

Actual behaviour:
- The tab is closed after a while.

**Comment by ray-lothian** [comment]
Thanks for the report. Will be fixed by the next release.
