### ISSUE TITLE
Could a page be blocked without a warning page popping out?

### ISSUE THREAD

**Issue by minshifu** [ray-lothian/Block-Site#65]
Thank you for your great addon. I have a little question. Could a webpage be blocked silently? Currently every page is blocked with a warning page popping out as shown below. Although I can make it disappear in as little as 1 second, could the warning page be completely dispensed with?

        Best regards!
         Edmond
![图片](https://user-images.githubusercontent.com/5119952/130338180-0244fe08-7132-41e8-acde-f2a4dc81dbdb.png)

**Comment by ray-lothian** [comment]
There is an option to auto-close this warning page on the options page. Also, you can always redirect to the "close" keyword if you want the extension to immediately close this page.
