### ISSUE TITLE
redirect to previous page

### ISSUE THREAD

**Issue by aquaphx** [ray-lothian/Block-Site#7]
would be nice if there's an option for blocked site to redirected to previous site

**Comment by ray-lothian** [comment]
how about using `javascript:` as the redirect URL? Use it with caution though since there is no warning. It is like the link is not working.

**Comment by aquaphx** [comment]
thanks..
is this correct ?

`https://imgur.com/a/Ph983DI`

**Comment by ray-lothian** [comment]
yes, `javascript:history.go(-1)` should work too.

**Comment by aquaphx** [comment]
thank you a lot for the help :) great extention
