### ISSUE TITLE
Reopening a tab of a restricted site does not ask for password

### ISSUE THREAD

**Issue by zrajnai** [ray-lothian/Block-Site#73]
My 9 year old figured out how to bypass Block Site by reopening the last closed tab which was restricted to her.

Steps to repro:
1. open site which is restricted
2. enter password to unblock site
3. close tab
4. right click on tab row, and click "Reopen Closed Tab"
Result:
restricted site will open without asking for password
Expected result:
password has to be entered for restricted site when reopening it from closed state

**Comment by ray-lothian** [comment]
Smart kid!

Whenever a page gets opened with the master password, the extension unblocks the hostname for the next 60 seconds. So you can even open the same page on a new tab or refresh the current page multiple times. This is meant for the page to load all its resources. After one minute though, everything goes back to normal. So I guess the "Reopen Closed Tab" will not work anymore. On Chrome/Edge, you can reduce the unblocking period. If you need to configure this hidden option, send me an email.

**Comment by zrajnai** [comment]
I'm on Firefox.
The page was closed for several minutes.
The kid had to reopen several tabs to get back to the given page.

**Comment by ray-lothian** [comment]
I just tried the FF version. Following your steps, I can restore the tab within the 1-minute window, but cannot restore it after one minute passed.

**Comment by zrajnai** [comment]
I think I found the problem.
The page was redirecting and I had to put a /* after the URL to block.

**Comment by zrajnai** [comment]
You can feel free to close this as 'not a bug'
