### ISSUE TITLE
sometimes blocked pages load when accessed via href on page 

### ISSUE THREAD

**Issue by rmmanseau** [ray-lothian/Block-Site#74]
Issue affects latest version of Chrome, 97.0.4692.71

These are the rules that I'm using:
R:^.*youtube\\.com\\/?(feed\\/(explore|subscriptions))?$
R:^.*reddit\\.com\\/?$

They block the home & explore pages, but let you access individual videos / subreddits.

Steps to reproduce on Youtube:
1. Navigate to a youtube link thats not blocked (any video)
2. Click the Youtube logo on the top left. The blocked URL loads.
3. Click on the explore or subscriptions buttons on the side bar. All blocked URLs load.
4. Refresh on a blocked page & the page is blocked.

Steps to reproduce on Reddit:
1. Navigate to a subreddit
2. Click the Reddit logo on the top left. The blocked URL loads.
3. Refresh and the page is blocked.

This issue appears to only affect chrome. I've verified that the rules work as intended on Firefox.

I think it's probably a caching or redirect issue or something.

**Comment by ray-lothian** [comment]
Thanks for the report. This is fixed by the next release. If not please reopen

**Comment by rmmanseau** [comment]
yup, appears to be fixed. thanks!
