### ISSUE TITLE
Resuming block after pause doesnt automatically redirect

### ISSUE THREAD

**Issue by sulphatet** [ray-lothian/Block-Site#76]
after blocking is resumed it doesn't automatically redirect for Reddit. Instead we need to refresh for the redirection to take place.

### Suggest: 
Send a notification every-time blocking is resumed to inform the user.

**Comment by amin-e** [comment]
The Chrome version displays a notification when the blocking is resumed;

https://github.com/ray-lothian/Block-Site/blob/9e1c9b1b39eeba31285bfdb5170a7955bd7b2931/v3/contextmenu.js#L135

What is your browser?

**Comment by sulphatet** [comment]
> The Chrome version displays a notification when the blocking is resumed;
> 
> https://github.com/ray-lothian/Block-Site/blob/9e1c9b1b39eeba31285bfdb5170a7955bd7b2931/v3/contextmenu.js#L135
> 
> What is your browser?

I use Firefox

**Comment by ray-lothian** [comment]
Firefox now uses an outdated version of this extension since it does not yet support manifest v3. Hopefully, it will get fixed by updating to the "v3" channel; https://github.com/ray-lothian/Block-Site/tree/master/v3
