### ISSUE TITLE
Version 0.1.9 compatibility

### ISSUE THREAD

**Issue by grahamperrin** [ray-lothian/Block-Site#8]
I see 

`"strict_min_version": "57.0"`

First impressions, with Waterfox 56.2.7.1 (Waterfox 56.0 was based on Firefox 56.0.2): the extension _does_ seem to work. Off the top of your head, do you know which features of 0.1.9 might be incompatible?

I can easily install 0.1.6 https://addons.mozilla.org/firefox/downloads/file/1149295/block_site-0.1.6-an+fx.xpi but I'm curious about the more recent version.

**Comment by ray-lothian** [comment]
Nothing is changed for Desktop version. This is the minimum FF for Android version to support all the APIs

**Comment by grahamperrin** [comment]
Thanks!
