### ISSUE TITLE
Problem with "Optional redirect URL"

### ISSUE THREAD

**Issue by Sinclair-ZX81** [ray-lothian/Block-Site#81]
Situation: If the browser (Firefox 98.0.2 64 bit) load the page https://live.vodafone.de/page/logout, the addon should redirect to www.startpage.com 

So I've set www.startpage.com as an "Optional redirect URL" next to my listed rule entry "https://live.vodafone.de/page/logout", saved the config ... but the redirect won't happen and the blocking information still comes up all the time as if no redirect was set: 

![grafik](https://user-images.githubusercontent.com/80591481/161547942-b98a084a-8b77-4a76-b597-108679624e92.png)

Curiously it's working, if the desired redirect URL was set down below in section "Blocked Page" -> "Redirect to:"

So I wonder what's the purpose of the field "Optional redirect URL" ... why isn't it useable for this case?

**Comment by ray-lothian** [comment]
Can you reproduce this on Chrome too? FF still uses the old version since it does not support manifest v3. I am not able to reproduce this on the latest release.

**Comment by Sinclair-ZX81** [comment]
Yepp, with Chrome  (100.0.4896.75 / 64 bit) it's not an issue!
But even with todays FF update at version 99 (64 Bit) it's still there ...

No chance for a fix?
I am just asking, because the redirection actually works when set in section "Blocked Page" -> "Redirect to:" ...

**Comment by ray-lothian** [comment]
I pushed a temporary fix until Firefox supports manifest v3. You need to save the options once you got the new version.

**Comment by Sinclair-ZX81** [comment]
Thanks - will check it as soon as it is available
