### ISSUE TITLE
"Cannot read properties of undefined" exception in dev tools on some pages (HTTPS related?)

### ISSUE THREAD

**Issue by beleester** [ray-lothian/Block-Site#85]
If I have the developer tools open, some websites will give an error every time the page first loads:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'getRegistrations')
    at page-blocker.js:38:25
```
Which corresponds to this line of code in page-blocker.js:

`navigator.serviceWorker.getRegistrations().then(registrations => {`

This file appears to be run by the Block Site extension on every page.

From my attempts to reproduce it, the issue seems related to whether or not HTTPS is in use on that page.  If you go to http://example.com with the developer tools open you'll see the error but if you go to https://example.com/ you won't.

This is a problem for me because I'm a software developer and I have Block Site installed on my work machine to help me focus, so I frequently have the dev tools open when working on a website, and this error keeps interrupting me.

Found in Chrome Version 102.0.5005.63 (Official Build) (64-bit)

**Comment by ray-lothian** [comment]
> This file appears to be run by the Block Site extension on every page.

True, it is used to make sure a cached version of the site is not loaded (when there is no network request involved).

Thanks for the report. The bug is fixed.
