### ISSUE TITLE
Option for "simple" scheduled blocking

### ISSUE THREAD

**Issue by dtw** [ray-lothian/Block-Site#87]
I'm sure there the change to scheduled unblocking is well intentioned but... I just want to block all the listed sites during my work hours.

Now I need to have two entries for every day to unblock before work and after work?

Should I just fork the last version and submit it to Mozilla as "Simple-Block-Site"?

**Comment by ray-lothian** [comment]
<img width="835" alt="Screenshot" src="https://user-images.githubusercontent.com/29911230/181416480-94b365c8-ebb0-4e67-9802-36b32be617b4.png">
Valid point. The next release has a simple converter tool on the top section to help you generate the periods.

> Should I just fork the last version and submit it to Mozilla as "Simple-Block-Site"?

"Block Site" is an open-source project. If you are willing to maintain yours, you are welcome to fork and republish.
