### ISSUE TITLE
Block-Site is not working

### ISSUE THREAD

**Issue by eric974** [ray-lothian/Block-Site#9]
Hello.
In the module manager the icon of your block site is grayed out and inoperative, with Firefox 66.0.5 (64 bits) and Windows 10 (x64) 1809.
Why? Can you help me?
Thank you.
Regards.
See 
![Block-Site](https://user-images.githubusercontent.com/50474432/57503118-e2def400-72ff-11e9-9b54-64610e5a696e.JPG)

**Comment by ray-lothian** [comment]
Hi,

This is just the new icon, it should work just fine as the options button is enabled
