### ISSUE TITLE
Cannot change parameters in Vivaldi Browser

### ISSUE THREAD

**Issue by Anton-V-K** [ray-lothian/Block-Site#94]
I'm using Block Site 0.4.8 with Vivaldi Browser 5.1.2567.73 (32-bit) on Windows 8.1 (64-bit).
Initial setup of parameters went fine and the addon functions as expected.
However any subsequent attempt to change the parameters is impossible - after entering the password the buttons `Save Options`, `Export (JSON File)` and `Import (JSON file)` become enabled, however I can't press them (they look like ignoring my clicks).

**Comment by Anton-V-K** [comment]
The issue seems to be related to Master Password handling - once you set the password, subsequent unlocking blocks the buttons `Save Options`, `Export (JSON File)` and `Import (JSON file)`, so you can't save anything.

**Comment by ray-lothian** [comment]
You need to enter the master password and press the "Unlock Options" button to have access to these buttons.

**Comment by Anton-V-K** [comment]
The issue seems to be happening in old versions of Vivaldi (5.1.2567.73 in my case).
Even Block Site 0.4.9 can't properly enable the mentioned buttons after entering the password: they look like enabled, but doesn't react on user clicks.
OS: Windows 8.1 / 10
Workaround: install newer version of Vivaldi (e.g., 5.6.2867.50)
