### ISSUE TITLE
debounce the block site button

### ISSUE THREAD

**Issue by Inc0n** [ray-lothian/Block-Site#96]
Clicking on the extension icon will result in ok cancel box asking to block the current site definitely.

I find myself to be to impatient with the icons, or sometimes misclicks. Which result in multiple of those popups. 
This can be annoying, as apparantly only the most recent popup (or least recent) can be closed first.
This behaviour can be learnt by users by adapting. But I would also think it's a good idea to debounce it button somehow to resolve this problem.

**Comment by ray-lothian** [comment]
Since the current implementation of the prompt window only supports a single instance, the extension will close the old ones when a new one is requested. This is a temporary fix for now.
